amr_core:
  ros__parameters:
    robot:
      ip: "192.168.1.1"
      port: 7272
      user: "admin"
      password: "admin"
      protocol: "6MTX"

    status:
      topic: "amr/status"
      battery_topic: "amr/battery_state"
      publish_period_ms: 200

    laser:
      main_laser:
        topic: "scan"
        frame_id: "laser_frame"
        request: "Laser_1Current"
        request_period_ms: 200
        angle_min: -2.09439510239
        angle_max: 2.09439510239
        angle_increment: 0.00872664626
        range_min: 0.02
        range_max: 40.0
      low_laser:
        enabled: true
        topic: "scan_low"
        frame_id: "laser_frame_low"
        request: "Laser_2Current"
        request_period_ms: 200
        angle_min: -1.09955742876
        angle_max: 1.09955742876
        angle_increment: 0.00872664626
        range_min: 0.02
        range_max: 4.0

    driver:
      odom_topic: "/odom"
      cmd_vel_topic: "/cmd_vel"
      stop_topic: "/stop"
      odom_frame: "odom"
      base_frame: "base_link"
      min_linear_speed: -200.0
      max_linear_speed: 1200.0
      min_angular_speed: -60.0
      max_angular_speed: 60.0
      drive_throttle_pct: 100.0
      unsafe_drive: true
      cmd_vel_timeout_sec: 0.2